import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CartProvider } from "./components/CartContext";
import Script from "next/script";
import { ClerkProvider} from "@clerk/nextjs";
import StoreProvider from "../../storeProvider/storeProvider"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>


  <ClerkProvider>
        <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <CartProvider>
   
      {children}
    
      </CartProvider>
        
      <Script src="//code.tidio.co/4f6jratycn0i22hlgfvavhju83j5nlky.js" async></Script>
      </body>
    </html>
  </ClerkProvider>
  </StoreProvider>
  );
}
